name: pkgdown

on:
  push:
    branches: [main]

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
      - name: Build and deploy pkgdown site
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
